// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKJMasqFhbSzUZZd9Zuf4UuDwXdPoV--I',
    appId: '1:550095908731:web:045180878db2b78ce357de',
    messagingSenderId: '550095908731',
    projectId: 'gdtest-9e96a',
    authDomain: 'gdtest-9e96a.firebaseapp.com',
    storageBucket: 'gdtest-9e96a.appspot.com',
    measurementId: 'G-Q14WWHKJX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmsWlAp_ImFsx4VRZ7VwDQIHzIwTyOriU',
    appId: '1:550095908731:android:795c2035eca17e94e357de',
    messagingSenderId: '550095908731',
    projectId: 'gdtest-9e96a',
    storageBucket: 'gdtest-9e96a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpR1lzM0ub6IcRq_Zyl0n_3nj9hkJSuec',
    appId: '1:550095908731:ios:837edc25acf65f4fe357de',
    messagingSenderId: '550095908731',
    projectId: 'gdtest-9e96a',
    storageBucket: 'gdtest-9e96a.appspot.com',
    iosBundleId: 'com.ansarjaved.gdtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpR1lzM0ub6IcRq_Zyl0n_3nj9hkJSuec',
    appId: '1:550095908731:ios:d0d599d0cb0dec03e357de',
    messagingSenderId: '550095908731',
    projectId: 'gdtest-9e96a',
    storageBucket: 'gdtest-9e96a.appspot.com',
    iosBundleId: 'com.ansarjaved.gdtest.RunnerTests',
  );
}
